# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Plucene-SearchEngine-Index-Image
version:      0.01
version_from: lib/Plucene/SearchEngine/Index/Image.pm
installdirs:  site
requires:
    Image::Info:                   0
    Plucene::SearchEngine::Index:  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
